### ISSUE TITLE
Email validation not working

### ISSUE THREAD

**Issue by 8devil3** [baldarn/open-GAS#5]
Hi Lorenzo, today I tried to register on [opengas.eu](https://opengas.eu/users/sign_up) using fake email addresses without domain extensions (something like _xulycy@mailinator_ or _test@test_).
The result was always an error (screenshot attached), probably due to not being able to send confirmation email.
The last time, I tried with the same email address used in past attempts and it confirms that the email was already present: this means that it saved my registration attempts to db anyway.
If you search on db filtering by today date you'll find some fake emails like the ones I already mentioned.

I also tried password validation and it works correctly checking string length and matching between password and confirmation password fields.

Browser: Chrome on macOs and Chrome on Android (smartphone).

![test-registrazione-opengas](https://github.com/user-attachments/assets/ae1627ba-e5aa-45e4-be28-b7c1c7a2d9be)

**Comment by baldarn** [comment]
based on email RFC, that email are valid. those could be pointing to a named host or something.

I'll remove the user 500 failure and mark this as done.

thanks for reporting!

**Comment by baldarn** [comment]
fixed here
https://github.com/baldarn/open-GAS/commit/d0b98e56290172033a4f83679fc8d68425d3ee72
